name: "Pre-commit"
description: 'Run and Settup Pre-commit'

inputs:
  filename:
    description: "Name of file previously inserted with pre-commit output."
    required: false
    default: 'something.txt'

outputs:
  output:
    description: 'Content of stdout'



runs:
  using: "composite"
  steps:

    - name: 'dependencies'
      run: |
        pip install html2text
        python ./.github/actions/pre-commit-output/dist/script.py $INPUT_FILENAME
      shell: bash
      env:
        GITHUB_WORKSPACE: ${{ github.workspace }}

    - name: 'fileContent'
      run: |
        echo $GITHUB_WORKSPACE
        echo $(cat ./something.txt)
        echo "::set-output name=output:: $(cat ./something.txt)"
      shell: bash
